[[Yosys]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "edb07f85200948b864a34f3e06d58e32d2d37c8d"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "b20d4383cb357b5d010ff4e6d0c0b66094773dc3a37d9961cba5333e204663db"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9ed08b4eacc2b9426feb8c6184ad597b50e8fc8"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "447ebbe0f16399f190f9c09a84f9efb6ef75fb19867d9f0e8c6d902af910e6d3"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.aarch64-linux-musl-cxx11.tar.gz"
[[Yosys]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9b67657596650822e9bfac09c69ed9577d76f403"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "bf7485ffa01d076960323d4237420e0a70e4577da6e4578d073812d6dd782d04"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Yosys]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c659fcea5f5277fd19b1374ff17188295dc10dc2"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "2084c203ce5b0b1c8af2e739eaf81bc2402454b48692f86c1a949d4b428ab115"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Yosys]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba847dda23c08abc2ccab187afe74940c4489aee"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "2aaedacb85326c74d5e3d35d5e3eb51651bf7c7d9222ca263dcd273a36088735"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.i686-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3de339d11fae7b175d4ac975c3add9ef78751130"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "108f3f0dc0b722bf8d96b7c068ac7361aad17a04180f9524b03e95e8f97eb5d6"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.i686-linux-musl-cxx11.tar.gz"
[[Yosys]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2059791b72e20fb3e52c0609eb04d15125a75cd"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "535aff2f3d27c2a5e626b68c4920b1479dab8849a3db6ec1a2a652546a8b7c74"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "x86_64"
git-tree-sha1 = "8d56348de1444742a2cfd8f728dcd4d94b3c5346"
os = "macos"

    [[Yosys.download]]
    sha256 = "7f56f76930d587ffc42369b977cf974d5705545c9bcec81e096c5e88c4181a55"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.x86_64-apple-darwin.tar.gz"
[[Yosys]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee90fc26a2b805001db9b7ed7aaf9604339e0eb6"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "89a070922c24b571e72e112419d851f9c98c622d2377c5077859225580d03171"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7da5b2e04a4f261456332c46dd39c6d0ad77ca83"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "3ebb563300aca935ffbb89c87c6b7bc5278b7a1b02b0b6a5f49d16e802f8de6a"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.9.0+0/Yosys.v0.9.0.x86_64-linux-musl-cxx11.tar.gz"
