[[Yosys]]
arch = "aarch64"
git-tree-sha1 = "926496441a230938cfb3db0d61801889ec45f1b4"
os = "macos"

    [[Yosys.download]]
    sha256 = "e783d63cf7659c1a00280884235f5826618e9fff710b81e475d84b78d6b2e2d5"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.aarch64-apple-darwin.tar.gz"
[[Yosys]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef9ed496f3edb90abfce266a9f10c8f36a44a3e4"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "890755f48f125075d4325e1dff1c87cfe7353ddae2f624813ef5d75f0acb0d2b"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e85f687b8aa5a81ec5a8f309cc7c75ba8f05f7e1"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "9a2411fd52893a9c66dd369dc31fbea630444506f462ac0505b0917d7cf3fc66"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.aarch64-linux-musl-cxx11.tar.gz"
[[Yosys]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "37f594faac91b1572c1a3a97394904410d1be5ea"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "a1f0c977cc7c73733fae57115a78c1340a07149207d5a8487b4b0d47541abfbe"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Yosys]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3257cc0728df34afb0a8dc5e1faf08ccab35ee9d"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "3bb85ea930fe0f0f3fa90fa8e7d64501269578f1f23845889debd3ce8e37ea54"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Yosys]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e10220372cdeca06ecdb383b59544f1ed8e087cb"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "65b24cd9426b8f3dbb758e00796306ccc485974782bb8b7495e62bcc67977597"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.i686-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e54ee6f38443abf9ce408fb8e9dc2290905d3dd"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "8749bbe6218db6486a25aa0c07ea250184aa9b14caa46926c1f9d57e7b881441"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.i686-linux-musl-cxx11.tar.gz"
[[Yosys]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b2ec08e77306da6f64c8543874e87c749d03cf38"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "f0807bb9fc9f8b3ee75b42f0f3ba4a02fcb0167409d931c67f96603a9c6349f2"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "x86_64"
git-tree-sha1 = "e87d829ac6f42b6f96d6bd06f84f3948a7fe2226"
os = "macos"

    [[Yosys.download]]
    sha256 = "d354fad1f7c2708b5f65b4cf6261fdb33985cf232ee88b0549d163fe82e811fb"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.x86_64-apple-darwin.tar.gz"
[[Yosys]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6318d9132446d8d16a48218f939dc6420d49dca5"
libc = "glibc"
os = "linux"

    [[Yosys.download]]
    sha256 = "56d230a9bf707bacc7a26e76ae7f55d82ab999bc3b976fd1af42c5052a497238"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Yosys]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8dcc7be7355559645c84a72c91f4175d710c769"
libc = "musl"
os = "linux"

    [[Yosys.download]]
    sha256 = "7778a7cbebe04b24a5bb895f9202b80f6be06b57ed5e5a760d27e42cc8c02ecb"
    url = "https://github.com/JuliaBinaryWrappers/Yosys_jll.jl/releases/download/Yosys-v0.11.0+0/Yosys.v0.11.0.x86_64-linux-musl-cxx11.tar.gz"
