# Autogenerated wrapper script for Yosys_jll for i686-w64-mingw32-cxx11
export libyosys, yosys, yosys_filterlib

using boost_jll
using Readline_jll
using Tcl_jll
using Zlib_jll
using Libffi_jll
using dlfcn_win32_jll
JLLWrappers.@generate_wrapper_header("Yosys")
JLLWrappers.@declare_library_product(libyosys, "libyosys.dll")
JLLWrappers.@declare_executable_product(yosys)
JLLWrappers.@declare_executable_product(yosys_filterlib)
function __init__()
    JLLWrappers.@generate_init_header(boost_jll, Readline_jll, Tcl_jll, Zlib_jll, Libffi_jll, dlfcn_win32_jll)
    JLLWrappers.@init_library_product(
        libyosys,
        "bin\\libyosys.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        yosys,
        "bin\\yosys.exe",
    )

    JLLWrappers.@init_executable_product(
        yosys_filterlib,
        "bin\\yosys-filterlib.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
